env:
  browser: true
  es6: true
  jest: true
extends: 
  - 'eslint:recommended'
  - 'airbnb-base'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  no-console: 0
  import/extensions: 0